project_id = "nljlvrrxtfimmiysfwxd"

[functions.ai-recommendations]
verify_jwt = true

[functions.ai-movie-review]
verify_jwt = true

[functions.ai-similar-movies]
verify_jwt = true

[functions.ai-watch-plan]
verify_jwt = true
